var friendsArr = [
    {
        "name":"Jeff",
        "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/3435aa3.jpg",
        "scores":[
            2,
            1,
            3,
            4,
            5,
            1,
            2,
            3,
            2,
            5
          ]
      },
      {
        "name":"Britta",
        "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/3435aa3.jpg",
        "scores":[
            2,
            2,
            5,
            5,
            4,
            1,
            1,
            2,
            3,
            4
          ]
      },
      {
        "name":"Abed",
        "photo":"",
        "scores":[
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3
          ]
      },
      {
        "name":"Troy",
        "photo":"",
        "scores":[
            1,
            3,
            4,
            5,
            5,
            5,
            3,
            4,
            1,
            2
          ]
      },
      {
        "name":"Pierce",
        "photo":"",
        "scores":[
            5,
            4,
            3,
            2,
            1,
            5,
            4,
            3,
            2,
            1
          ]
      },
      {
        "name":"Shirley",
        "photo":"",
        "scores":[
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5
          ]
      },
      {
        "name":"Chang",
        "photo":"",
        "scores":[
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
          ]
      }  
    ]
    
    module.exports = {friendsArr:friendsArr};